language: node_js

node_js:
  - stable

before_script:
  - cd client && yarn
  - cd ../server && yarn
  - cd ..

jobs:
  include:
    - stage: Lint client
      script: cd client && yarn run lint
    - state: Build client
      script: cd client && yarn build
    - state: Lint server
      script: cd server && yarn run lint
