version: "3"
services:
  client:
    network_mode: host
    build: ./client
    ports:
      - "3000:3000"
    depends_on:
      - server
  server:
    network_mode: host
    build: ./server
    ports:
      - "8080:8080"
