version: "3"
services:
  redis:
    network_mode: host
    image: "bitnami/redis:latest"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
  client:
    network_mode: host
    build: ./client
    ports:
      - "3000:3000"
    depends_on:
      - server
  server:
    network_mode: host
    build: ./server
    ports:
      - "8080:8080"
    depends_on:
      - redis
