import React from 'react';

export const Spinner = () => (
  <>
    <div className="loadingio-spinner-dual-ring-6nx2xgln5mq">
      <div className="ldio-p7ic7jgj93g">
        <div></div>
        <div>
          <div></div>
        </div>
      </div>
    </div>

    <style jsx>{`
      @keyframes ldio-p7ic7jgj93g {
        0% { transform: rotate(0) }
        100% { transform: rotate(360deg) }
      }
      .ldio-p7ic7jgj93g div { box-sizing: border-box!important }
      .ldio-p7ic7jgj93g > div {
        position: absolute;
        width: 50px;
        height: 50px;
        top: 28px;
        left: 28px;
        border-radius: 50%;
        border: 16px solid #000;
        border-color: #0784f9 transparent #0784f9 transparent;
        animation: ldio-p7ic7jgj93g 1s linear infinite;
      }
      .ldio-p7ic7jgj93g > div:nth-child(2) { border-color: transparent }
      .ldio-p7ic7jgj93g > div:nth-child(2) div {
        position: absolute;
        width: 100%;
        height: 100%;
        transform: rotate(45deg);
      }
      .ldio-p7ic7jgj93g > div:nth-child(2) div:before, .ldio-p7ic7jgj93g > div:nth-child(2) div:after {
        content: "";
        display: block;
        position: absolute;
        width: 16px;
        height: 16px;
        top: -16px;
        left: 48px;
        border-radius: 50%;
        box-shadow: 0 128px 0 0 #0784f9;
      }
      .ldio-p7ic7jgj93g > div:nth-child(2) div:after {
        left: -16px;
        top: 48px;
        box-shadow: 128px 0 0 0 #0784f9;
      }
      .loadingio-spinner-dual-ring-6nx2xgln5mq {
        width: 200px;
        height: 200px;
        display: inline-block;
        overflow: hidden;
        background: #f1f2f3;
      }
      .ldio-p7ic7jgj93g {
        width: 100%;
        height: 100%;
        position: relative;
        transform: translateZ(0) scale(1);
        backface-visibility: hidden;
        transform-origin: 0 0; /* see note above */
      }
      .ldio-p7ic7jgj93g div { box-sizing: content-box; }
      /* generated by https://loading.io/ */
      </style>
    `}</style>
  </>
);
